### PR TITLE
added part 2 of iMAD tutorial

### PR DESCRIPTION
**Pull request by mortcanty**
This is the second part of the three part iMAD community tutorial

### CODE REVIEW

**Comment by jdbcode** [comment]
Thanks for the PR, Mort. I'll be looking soon.

**Comment by jdbcode** [comment]
The steps:

- [ ] I'll do minor review on the notebook file in this pull request
- [ ] You make any suggested changes from the review, commit them here
- [ ] I'll check changes and say "looks good"
- [ ] You move/copy the "looks good" notebook file into a repo in your GitHub account (similar to [part](https://github.com/mortcanty/eeimad/blob/main/src/gee_change_detection_pt_1.ipynb))
- [ ] I'll send a markdown version of it to you and you commit it to this pull request and remove the notebook
- [ ] I'll approve the pull request and make sure that it publishes correctly

**Comment by mortcanty** [comment]
Thanks again as usual, Justin. Will do

**Comment by mortcanty** [comment]
Hey Justin, taking a while. I hope there's not a problem with content. Best

**Comment by jdbcode** [comment]
Sorry this is taking so long, Mort. I made progress today. Part of the problem is the review and editing tools for notebooks that I've been using are not great (not a fun time). However, I've discovered today that Visual Studio Code allows one to edit the formatted notebook cells and it makes the proper changes to the JSON automatically, and can show dif simultaneously (makes me very happy!). It's only been nit picky things to change, but I figure as I'm going through the tutorial I might as well fix them. Anyway, getting there, just slowly :)

**Comment by mortcanty** [comment]
Thanks for the update Justin. Again, sorry this python API stuff is such a nuisance to publish.

**Comment by jdbcode** [comment]
Mort, the analysis and text look good. I made some formatting edits and committed them in this PR. Will you download and run this .ipynb commit in Colab as a double check that for my edits didn't mess anything up?

https://raw.githubusercontent.com/google/earthengine-community/97c1c0dd5221f796333610f5866c39291b8f18d6/tutorials/imad-tutorial-pt2/index.ipynb

**Comment by jdbcode** [comment]
Use this for testing: https://raw.githubusercontent.com/google/earthengine-community/b4746696161eb49e7dcbabdd4bb6dfb608eb7291/tutorials/imad-tutorial-pt2/index.ipynb

**Comment by mortcanty** [comment]
Just ran it through on Colab. Runs just fine.

**Review by jdbcode — APPROVED** [review]

**Comment by jdbcode** [comment]
Thanks, Mort! The tutorial is being merged to Google code base where I'll render the page and check it. Sometimes small formatting changes to latex formula are needed (mostly indicators for what is formula, though Gino has fixed most of these).
I'll make any format changes needed and then let you know when it goes live.

**Comment by jdbcode** [comment]
Mort, Part 2 is live!

https://developers.google.com/earth-engine/tutorials/community/imad-tutorial-pt2

**Pull request merged**
