### PR TITLE
Corrected two small typos to formulae in Part 2

### PR DESCRIPTION
**Pull request by mortcanty**
@jdbcode Sorry, as you suspected, I edited an older version of part 2, so creating a new pull request after re-forking toh repo.

### CODE REVIEW

**Comment by jdbcode** [comment]
Thanks, Mort. The difference is whole, so can you confirm that these are the intended changes.

**Change 1**:

From:
image
To:
image

**Change 2**:

From:
image
To:
image

Can you confirm that application of this ^ equation is correct:
```
m2logQ = det(im1).log().add(det(im2).log()).subtract(
    det(im1.add(im2)).log().multiply(2)).add(4*np.log(2)).multiply(-2*m)
```

**Comment by jdbcode** [comment]
Hi Mort, can you please confirm the two changes above. The GitHub change tracker is not helpful in this case because the entire file shows up as changed. I found the changes by visual comparison, I'm just wanting to make sure I understand what has changed. Thanks.

**Comment by mortcanty** [comment]
@jdbcode Sorry, I confirmed by email reply last week. Forgot to do it here in the PR - Git novice :( Anyway, those are the correct changes. Thanks.

**Comment by jdbcode** [comment]
My apologies, Mort. I must have missed the email. Thanks for confirming the changes. I've made the changes in PR #273 to maintain the rest of the file so that change tracking is easier. Once #273 is merged, it will close this PR.

**Review by gino-m — APPROVED** [review]
LGTM! Thanks for the attention to detail.

**Pull request merged**
