### PR TITLE
Add Species Distribution Modeling Tutorial

### PR DESCRIPTION
**Pull request by osgeokr**
I have completed writing the tutorial "Species Distribution Modeling with Google Earth Engine" previously accepted in #776.

### CODE REVIEW

**Comment by jdbcode** [comment]
Thanks for fixing the issues that came up during automated checks! All have passed. I should be able to review by the end of next week.

**Comment by jdbcode** [comment]
@osgeokr you've done an amazing job! This is one of the best tutorials I reviewed and the analyses is really useful. Thank you!

I left some comments that are mostly nits about code formatting and style and a couple suggestions for alternative implementations. You should be able to see comments in context using the ReviewNB links above.

Common formatting and style nits:

- Aim for 80 char line length (some are too long)
- Aim for consistency with variable name (best to use snake_case)
- Remove all outputs

The Black Python code formatter is good for line length fixing - there is a command line version (I don't think it works on notebooks though), but there is a UI for it that is nice for copy/paste as few blocks of code: https://black.vercel.app/

Please address the comments or reply to them for discussion or clarification. Once all the comments are addressed, please commit your changes and I'll look again.

Thanks,
Justin

**Comment by osgeokr** [comment]
Thank you sincerely for your meticulous review! Working on the tutorial has enhanced my understanding of GEE, for which I am grateful. I have quickly gone through all the reviews you provided and have no further objections, so I will proceed to revise and commit the changes accordingly. I believe it will be possible within this week.

**Comment by osgeokr** [comment]
I have committed the updated file with the modifications to the comments you provided. Thanks a lot!

**Comment by jdbcode** [comment]
@osgeokr - thank you for the updates! I should be able to look in the next few days.

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257583'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257602'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257660'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257676'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257690'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257719'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257732'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257752'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257755'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257773'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257789'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257822'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done	</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257844'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257854'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257808'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jdbcode** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/google/earthengine-community/pull/789/discussion/#comment-1955257636'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by jdbcode — APPROVED** [review]

**Review by sgreenberg — APPROVED** [review]

**Review by sgreenberg — APPROVED** [review]

**Comment by jdbcode** [comment]
@osgeokr, thank you for the edits! Everything looks great - nice job! Next, the files will be pulled into Google and the page will be built and hosted on DevSite. It might be another week before it is live. I'll post the link in the PR when the page is finally published.

**Comment by osgeokr** [comment]
@jdbcode I am truly happy to play a small role in the Earth Engine Community! I sincerely appreciate all your help in this regard!

**Comment by jdbcode** [comment]
Congratulations, the page is live! Here is the link: https://developers.google.com/earth-engine/tutorials/community/species-distribution-modeling

You can also find it on the tutorial explorer page: https://developers.google.com/earth-engine/tutorials/community/explore#python_api_tutorials

And in the left navigation panel table of contents.

Thank you so much for the excellent tutorial and supporting the Earth Engine developer community!

Please let me know if you see any issues, you can also make any changes with another pull request. One thing I noticed is that the page building procedure did not generate static images from the geemap outputs. For instance, you can see them in this tutorial (https://developers.google.com/earth-engine/tutorials/community/imad-tutorial-pt1). I'll try to figure out what is going wrong.

**Pull request merged**
