### PR TITLE
Updated the images for difference and intersection

### PR DESCRIPTION
**Pull request by TC25**

### CODE REVIEW

**Comment by TC25** [comment]
@gino-m For some reason, this has not been updated on the website. Do you know what could be the issue?

**Comment by jdbcode** [comment]
@TC25 thanks for the heads up! Looking into it.

@gino-m please check incoming review request.

**Comment by jdbcode** [comment]
@TC25 the changes should be published now.

https://developers.google.com/earth-engine/tutorials/community/beginners-cookbook

**Comment by TC25** [comment]
Thanks, @jdbcode

**Pull request merged**
