### PR TITLE
[Community tutorial] Estimating Groundwater Recharge Using Earth Engine Datasets 

### LINKED ISSUE #414: [Tutorial proposal] Estimating Groundwater Recharge Using Earth Engine Datasets
Hello everyone, 

I would like to submit you the idea of a new tutorial that could fit into the pyhton section of the earth egine community tutorials.

**What is the objective of the proposed tutorial?**
The objective of the tutorial is to calculate groundwater recharge rate at a given location using (1) meteorological datasets and (2) soil profile datasets.

In this tutorial, users will learn how to access (1) physical properties of soil around a place and (2) meteorological records to feed an iterative procedure implemented outside of the eath engine environment.

**What is the scope of the proposed tutorial?**
This tutorial focus on water resources management.

**Please provide an outline of the structure of the proposed tutorial?**
*1. Introduction*
- why calculating groundwater recharge
- aim and structure of the tutorial

*2. Run me first*
- initialization of theearth engine API, 
- import of librairies
- definition of the location and period of interest and visualization with folium

*3. Getting soil properties*
- introduction to Saxton & Rawls (2006) equations to link hydraulic properties of soil to texture properties,
- exploration of soil texture datasets (OpenLandMap)
- definition of a function to get the soil texture and content for a given location,
- definition of a function to calculate the wilting and field capacity of soil,

*4. Getting meteorological records*
- definition of a function to get precipitation and potential evapotranspiration records for a given location
- transformation into a dataframe

*5. Implementation of the Thornwaite-Mather (TM) procedure*
- description of the TM procedure to calculate groundwater recharge
- definition of a function to run the TM procedure. 
- calculation of the recharge at our location of interest

*6. Compilation and comparison between multiple places*
- definition of un function combining all steps and function previously defined,
- calculation and comparison of groundwater recharge fluctuations between two places.

*7. Bibliography*
- list of references used in the tutorial

**In what format will you be submitting the tutorial?**
[Colab]

Best regards,

This request will be reviewed by the Earth Engine community maintainers, who
will reply on this issue tracker with any questions or suggestions. Once
approved, this issue will be assigned to you and you can begin work on the
tutorial following instructions in
[Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write).
When creating your Pull Request, enter "Closes #issueno" in the description of
your Pull Request to link the tutorial to this issue.

### PR DESCRIPTION
**Pull request by guiattard**
Hi,

Please find the initial version of the tutorial (proposal #414). 

In the last section, you may see that a `ee.Image.reduceResolution()` would probably be desirable somewhere. I was not sure about the write place to apply it to not. Could you tell me what do you think about it?

I am also wondering about one point. In the last chapter, I introduce the effective plant rooting depth which is assumed to be a constant `ee.Image`. As explained in the tutorial, a global dataset is available for this parameter (see the publication [here](https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2016WR019392)) The journal is excellent so the consideration of this dataset would be valuable but:
•	the resolution of the dataset is much lower than other datasets used in the tutorial, 
•	the dataset is not available in the Earth Engine Data Catalog so the upload as a new asset would be needed,
•	the dataset is a TIFF without special reference. Hence, I guess some extra non-trivial manipulations would be needed before importing the resulting geoTIFF as an asset. In my opinion it would become out of the ‘earth engine’ scope.

Currently, I do not see a solution that would not overload to much the last part of the tutorial (which looks already dense). What do you think?

Otherwise, I hope you'll enjoy the piece.

Regards,

Closes #414

### CODE REVIEW

**Comment by jdbcode** [comment]
Guillaume, well done on the tutorial!

It is a long one, so it'll be helpful for me to do the review in a couple of iterations. Generally the layout of the sections, the supporting text, and the code are good and I have no major comments or concerns following my initial read through / code test.

For this first iteration, I've noted minor spelling, formatting issues, and a few things that "stuck out". Since the comments are mostly broadly applicable, I'll provide them here, instead of by-cell in ReviewNB. Please address the following comments throughout the tutorial and then commit your changes and I'll take a second look. I look forward to seeing the edits!

- Spelling and grammar issues. Here is [a Google Doc with spelling/grammer check highlighting](https://docs.google.com/document/d/16xh4PAW4EW8aRSlL6LGbXugVSG6k09upMOnvA51VBtc/edit?usp=sharing).
- In first map sand is shown, but in the following point sampling you use clay, as a reader I was expecting to see sand, I suggest changing from sand to clay.
- The locations you use, do they have any significance? The tutorial would be more meaningful if you can describe the location briefly e.g. "a productive agricultural region outside of Lyon, France", it helps make the content more relatable, gives context, of general interest to people.
- You mix snake_case and camelCamel case -- [please use this as a guide for consistency](https://google.github.io/styleguide/pyguide.html#316-naming).
- Use hyperlinks when referring to datasets in the Earth Engine Data Catalog.
- The first time you use `ee.Image.sample` and `ee.Image.getRegion` briefly describe what they do or hyperlink to their API reference page and make it clear that the computation is happening server-side and then you transfer the request results client-side. (e.g. [`sample` reference page](https://developers.google.com/earth-engine/apidocs/ee-image-sample)).
- In general the first time you specifcaly mention a function that might be unclear to people it would be nice to have a hyperlink to the respective API reference page or EE Guide page example (see API ref page example just above). I'm thinking about `expression` and `iterate`, specifically.
- Be consistent with code comments e.g. I see inconsistencies in space between # and start of comment, whether first letter is capitalized or not, and whether a period is used or not. My preference is like this:

```
# Code comment starts with capital letter and end with period.
```

- As best as you can estimate, keep code line length to 80 char
- Remove "We" from start of code comments e.g. "We select the precipitation" to "Select the precipitation"
- Consider importing `pprint` at the beginning and using `pprint.pprint` when printing long, messy looking outputs e.g.:

```
import pprint
pr_m = sum_resampler(pr, 1, 'month', 1, 'PR')
pprint.pprint(pr_m.getRegion(poi, scale).getInfo()[:5])
```

- `meteo_arr = meteo.getRegion(poi, scale).getInfo()` is called twice, the first time the result is just printed, the second time stored as a variable. Consider re-working these two cells so the request is made only once.
- A brief explanation of significant outputs would be helpful. Specifically, I'm thinking of the charts, just a sentence or two explaining the pattern you see with the goal to get readers thinking about how to interpret the result.
- Ensure consistent use of single (') or double (") quote for strings.
- You have a couple code sections where you add 4 or 5 bands to an image and you reuse `addBands` for each band being added. Consider using a list instead e.g.: `addBands([add, these, bands])`
- The `autolabel` function is defined twice – is it the same function? If so, no need to define again, if not, consider renaming.
- "Point of interest 1" and "point of interest 2" in the final map could be named more descriptively to make relatable, less generic.
- Final map, add a text cell following the map output that describes the color gradient and a brief narration of patterns you see to help readers begin to interpret the map and what it means.

**Comment by guiattard** [comment]
Hi @jdbcode,

Thanks for the review. Please find the revised version. My initial thought about the need of a `reduceResolution()` is not addressed yet (see my first message on top of this PR). I prefer to take your advice first.

Looking forward to reading you. And ready for the next iteration ;-)

**Comment by jdbcode** [comment]
Guillaume, thanks for the edits!
I'm at the AGU conference this week, so probably won't be able to look until next week. I've been trying to get some work done before and after attending the Earth Engine booth, but can't promise anything :)

**Comment by guiattard** [comment]
Hi Justin. Fine, there is no rush on my side. Have a nice AGU meeting. 

Cheers

**Comment by guiattard** [comment]
Hi Justin,

I whish you the best for the new year ! Hope you had great holidays.

Just to organize myself: should I expect an update in the following days?

Regards,

**Comment by jdbcode** [comment]
Hi Guillaume, I hope you had a nice holiday season too!
I'll be back to work tomorrow, I'll plan on looking at your changes in the morning. It would be nice to have this all finished up by the end of the week--I think it is possible. Thanks for your patience during the last month as AGU and holidays have interrupted my regular work activities.

**Comment by jdbcode** [comment]
Guillaume, thanks for addressing all of my comments—the changes are great! Thanks for applying the code formatting, it looks really nice, very easy to read.

A few things:

- I have a series of final grammar nit fixes, one variable name change (`my_list` -> `image_list`), and wrapping list of added bands in `ee.Image` for consistency with "allowed" arguments (e.g. `initial_rech.addBands(ee.Image([initial_apwl, initial_st, initial_pr, initial_pet]))`). **Instead of making comments for these, I've edited the .ipynb file to save us both time. I'm wondering if it is okay with you if I commit the changes directly in this PR?**
- Regarding potentially using `ee.Image.reduceResolution()`, can you describe this more, like what outputs/sections are you thinking it might be applied to?
- Regarding the effective plant rooting depth dataset. I think that we should go forward with the tutorial as is using the constant. The tutorial gives people enough information to change these parameters as needed, and as you say, it will be difficult to get it ingested (the best opportunity might be [Earth Engine Community Datasets archive](https://github.com/samapriya/awesome-gee-community-datasets)). We can update the tutorial in the future to take advantage of it, if it become more readily available in GEE.

Please let me know if it is okay to commit changes in this PR to the .ipynb file mentioned in the first bullet. You can see the [edited notebook here](https://colab.research.google.com/drive/1NYJL5R4MWZ-04fVp8cajlqWwGN__6cmO?usp=sharing) (sorry the changes won't be obvious).

**Comment by guiattard** [comment]
Hi Justin, 

Thank you very much for the review. I’ve checked the revised version and I only have one comment regarding the following sentence: 
> The resulting map represents the averaged annual precipitation and groundwater recharge rate in France over the period 2015-2020.

The period is actually 2015-2019 and not “2015-2020”.

I think there is enough material in the current version of the tutorial and not sure any more about the necessity to introduce the `Image.reduceResolution()` method. It would have been interesting to illustrate how to use this method to handle the color strip effect observed on the recharge map (caused by the manipulation of datasets with different scales) but not mandatory in my opinion.

I am okay to keep the rooting depth constant.

You can modify the period (2015-2019) and commit the changes 😉

Cheers,

**Comment by jdbcode** [comment]
Sounds good!

- I'll change "2015-2020" to "2015-2019" as you noted and commit all the changes
- ee.Image.reduceResolution(), I agree that there is probably enough in this tutorial without it. It could actually be a useful small tutorial on its own, that could use this current tutorial as a case study. For the future :)

**Comment by jdbcode** [comment]
LGTM/approve from me on content, code, formatting.
Over to @gino-m for a production check.

**Comment by guiattard** [comment]
Thanks Justin, it's been a pleasure ;-)

**Comment by jdbcode** [comment]
Just a quick update... the Python-based tutorials have live outputs in the Developer Guide pages, to generate them we have to replicate the notebook environment including all imported packages. We are in the process of ensuring all of the packages are available to us. It may take some time as we need assistance from a group outside of the Earth Engine team. I believe the package of concern is `branca.colormap` since we have tutorials successfully published using the other packages. Sorry for the delay.

**Comment by guiattard** [comment]
Hi Justin,

Sorry about the trouble caused by my two colormap lines 😅.

Please tell me if you want me to think about an alternative to display the caption on the last interactive folium map.

Regards,

**Comment by jdbcode** [comment]
No worries, let's see what happens with the tests first, it could be fine, just take a bit more time to get it figured out :)

**Comment by gino-m** [comment]
> Sorry about the trouble caused by my two colormap lines 😅.

No trouble at all. It's a useful exercise, since it will improve out ability to test notebooks manually before publishing. Thanks for your patience!

**Comment by guiattard** [comment]
Hi @gino-m and @jdbcode, do you have some good news about the publication process ?

Regards,

**Comment by guiattard** [comment]
Thanks for the update!

**Comment by gino-m** [comment]
> Thanks for the update!

Hi @guiattard, thanks for your patience while we add some tooling to be able to test notebooks with dependencies like this one. We're still working on getting that added; I hope to have something working this week. I'll update you towards the end of the week on progress. Sorry for the wait!

**Comment by guiattard** [comment]
Hi, just to tell you that I've detected a typo regarding the reference "Yang et al. (2016)".

In the main text, 

> depth dataset is provided by Yand et al. (2016)

 should actually be 

> depth dataset is provided by **Yang** et al. (2016)

Cheers,

**Comment by guiattard** [comment]
Hi,

Thanks for the publication of the tutorial!

There is something strange with the two interactive folium maps: the calculated layers are not visible although ticked in the layer control panel. 

It looks like the earth Engine token used to make the calculation expired.

Regards,

**Comment by jdbcode** [comment]
Hi Guillaume, there was a build issue over the weekend. We're looking into it.

**Comment by jdbcode** [comment]
Guillaume, I just checked on the tutorial and it seems like the outputs are correct now. Can you confirm that the issue you saw is gone.

**Comment by guiattard** [comment]
Hi Justin,

I have checked and the tutorial now looks wonderfull 🙂!

Thanks again for your support !

**Comment by jdbcode** [comment]
Great, thanks for confirming!
It's a pleasure working with you on these tutorials :)

**Comment by guiattard** [comment]
Hi Justin. I am glad you like it. Would you be interested to discuss privately about the possibility to go further in the elaboration of these kind of educational resources?

**Pull request merged**
