### PR TITLE
Update tutorials with signed CLA email

### PR DESCRIPTION
**Pull request by nasa-gsfc-soilmoisture**
#648

### CODE REVIEW

**Comment by jdbcode** [comment]
Great success–tests passed! Thanks for the changes. All is set on your end for now, we'll get to the review shortly.

**Comment by nasa-gsfc-soilmoisture** [comment]
Thank you for your help!!

**Comment by nasa-gsfc-soilmoisture** [comment]
Justin,

This tutorial is in support of a live training for the US forest service on April 25th. Could you please check this tutorial at your earliest convenience so it can be posted before the training?

Thanks

**Comment by jdbcode** [comment]
Hung, the tutorial looks good. I corrected some formatting as I went through it (see the 3 commits above). I have three recommendations for improvement.

1. Show an example of the three "layers" surface, subsurface, and precip in the map. Just select a given observation (from same time period) - it doesn't need to be meaningful, except to show users the variance in the variables across space.

2. Section 4 and 5 perform the exact same thing. My recommendation is to combine them.

```js
var ssSusMa =  nasa_usda_smap
  .filterDate(startDate, endDate)
  .sort('system:time_start', true)  // sort a collection in ascending order
  .select(['ssma', 'susma'])  // surface and subsurface soil moisture bands

// Compute monthly anomalies surface soil moisture.
var monthlySsSusMa =  ee.ImageCollection.fromImages(
  years.map(function(y) {
    return months.map(function(m) {
      var filtered = ssSusMa.filter(ee.Filter.calendarRange(y, y, 'year'))
                         .filter(ee.Filter.calendarRange(m, m, 'month'))
                         .mean();
      return filtered.set(
        'system:time_start', ee.Date.fromYMD(y, m, 1).millis());
    });
  }).flatten()
);
```

This might mean that you don't need to combine surface and subsurface collections later on - it should still chart okay. (this is untested).

3. Don't `clip` all images (see [best practices](https://developers.google.com/earth-engine/guides/best_practices#if-you-dont-need-to-clip,-dont-use-clip)). The charting function will do the clipping required for the chart. If you show layers on the map, you can clip the single image e.g. `Map.addLayer(thisParticularImg.clip(region))`. I removed `clip` in the above suggestion for combining sections 4 and 5, it can be removed from section 6 and also the `aoiClip` function can be removed.

---------------

You can make edits right here on GitHub - go to this [URL](https://github.com/google/earthengine-community/pull/651/commits/c7fa1b4d2d6a494c44507fcecbe4d46ee45388b2) - click on the three dot options on right of page and select "Edit" - make your changes and then commit them (very bottom of the edit page).

Let me know if you have any questions or would like to discuss anything.

**Comment by nasa-gsfc-soilmoisture** [comment]
> Hung, the tutorial looks good. I corrected some formatting as I went through it (see the 3 commits above). I have three recommendations for improvement.
> 
> 1. Show an example of the three "layers" surface, subsurface, and precip in the map. Just select a given observation (from same time period) - it doesn't need to be meaningful, except to show users the variance in the variables across space.
> 2. Section 4 and 5 perform the exact same thing. My recommendation is to combine them.
> 
> ```js
> var ssSusMa =  nasa_usda_smap
>   .filterDate(startDate, endDate)
>   .sort('system:time_start', true)  // sort a collection in ascending order
>   .select(['ssma', 'susma'])  // surface and subsurface soil moisture bands
> 
> // Compute monthly anomalies surface soil moisture.
> var monthlySsSusMa =  ee.ImageCollection.fromImages(
>   years.map(function(y) {
>     return months.map(function(m) {
>       var filtered = ssSusMa.filter(ee.Filter.calendarRange(y, y, 'year'))
>                          .filter(ee.Filter.calendarRange(m, m, 'month'))
>                          .mean();
>       return filtered.set(
>         'system:time_start', ee.Date.fromYMD(y, m, 1).millis());
>     });
>   }).flatten()
> );
> ```
> 
> This might mean that you don't need to combine surface and subsurface collections later on - it should still chart okay. (this is untested).
> 
> 3. Don't `clip` all images (see [best practices](https://developers.google.com/earth-engine/guides/best_practices#if-you-dont-need-to-clip,-dont-use-clip)). The charting function will do the clipping required for the chart. If you show layers on the map, you can clip the single image e.g. `Map.addLayer(thisParticularImg.clip(region))`. I removed `clip` in the above suggestion for combining sections 4 and 5, it can be removed from section 6 and also the `aoiClip` function can be removed.
> 
> You can make edits right here on GitHub - go to this [URL](https://github.com/google/earthengine-community/pull/651/commits/c7fa1b4d2d6a494c44507fcecbe4d46ee45388b2) - click on the three dot options on right of page and select "Edit" - make your changes and then commit them (very bottom of the edit page).
> 
> Let me know if you have any questions or would like to discuss anything.

I really appreciate your recommendation; it makes the script more cohesive!

I wonder if I can check my scripts running on GitHub instead of copying them to Code Engine, running them, and copying them back.

Hung

**Comment by nasa-gsfc-soilmoisture** [comment]
Justin, it looks good for me! Thanks so much for your help!

**Review by jdbcode — APPROVED** [review]

**Comment by jdbcode** [comment]
Congratulations, the tutorial has been merged. Thanks for supporting the Earth Engine developer community with this contribution!

Once the tutorial is published to the Earth Engine Developer Guide, I'll post the link here.

**Comment by jdbcode** [comment]
The tutorial is live!

https://developers.google.com/earth-engine/tutorials/community/anomalies-analysis-smo-and-pre

If you'd like to make changes to it in the future, you can sync your fork of the https://github.com/google/earthengine-community repository, edit the index.md file and submit a pull request.

**Pull request merged**
