### PR TITLE
A small fix in date formatting

### PR DESCRIPTION
**Pull request by LucasAgro**
Replaces "datetimeFormat: 'YYYY-MM-dd HH:MM:ss'" with "datetimeFormat: 'YYYY-MM-dd HH:mm:ss'"

### CODE REVIEW

**Comment by jdbcode** [comment]
Hi @LucasAgro, thanks for the fix! To contribute to the google/earthengine-community repo you'll need to sign the Contributor License Agreement (see the message above). If you'd rather not, I can make the change -- please let me know how you'd like to proceed.

**Comment by LucasAgro** [comment]
@googlebot I signed it!

**Comment by LucasAgro** [comment]
Thanks for your reply @jdbcode 
I signed the Contributor License Agreement.

**Review by jdbcode — APPROVED** [review]

**Comment by jdbcode** [comment]
@LucasAgro the change will be merged soon, thanks for your patience!

**Comment by jdbcode** [comment]
@LucasAgro, now that the PR is merged it will take a few days for the changes to be published to the Developer Guide. Thanks again for the fix!

**Pull request merged**
