### PR TITLE
added part 3 of imad tutorial

### PR DESCRIPTION
**Pull request by mortcanty**
Third and last part of the iMAD Tutorial,  explaining on how to use unchanged pixels identified by the iMAD algorithm to perform relative radiometric normalization of image pairs.

### CODE REVIEW

**Comment by jdbcode** [comment]
Thanks, Mort! I have time to get through this next week.

**Comment by jdbcode** [comment]
Hi Mort, I'm about 95% through the review. I'm waiting on the last two exports to complete. I'll pick it up again tomorrow. It looks great. At this point I have a series of small grammar and formatting changes, so I'll just commit the changes and you can let me know if you're okay with them, instead of providing you a list of suggested changes for you to make.

**Comment by mortcanty** [comment]
Great Justin. Many thanks again for your help with the whole series!

**Comment by jdbcode** [comment]
Did you catch the commit note? Maybe I shouldn't be the one checking ~~grammer~~ grammar 🙃😀

**Comment by jdbcode** [comment]
I'm checking on how formatting in DevSite looks. Once I confirm it's okay, I'll email you the Markdown version so you can replace it with the .ipynb file.

**Comment by mortcanty** [comment]
Good thing you're on to it nevertheless. Dyslexia is my speciality ✍🙄

Justin Braaten ***@***.***> schrieb am Fr., 9. Juni 2023,
19:35:

**Comment by jdbcode** [comment]
Mort, I emailed next steps to you.

**Comment by mortcanty** [comment]
Justin, followed your instructions. I think the failed check above is due to not removing the original .ipynb notebook from the PR.

**Comment by jdbcode** [comment]
Yes, that seems to be the case

> AssertionError: dirs must contain exactly one index.md or *.ipynb

Are you able to remove it from your end?

Since there is a copy here (https://github.com/mortcanty/eeimad/blob/main/src/gee_change_detection_pt_3.ipynb), it all looks good. I mean the .md file in this PR links to it and is valid, so okay to remove the .ipynb file from this PR.

**Review by jdbcode — APPROVED** [review]

**Comment by jdbcode** [comment]
All looks good, Mort, thanks!

It'll now take a few days to get through the pipeline on our side. I'll post here when it goes live.

**Pull request merged**
