### PR TITLE
Community tutorial on web app development

### PR DESCRIPTION
**Pull request by TC25**
Let me know if this is appropriate and suggest improvements if needed.

### CODE REVIEW

**Comment by jdbcode** [comment]
Hi TC, thanks for submitting this tutorial!
There is another in the queue that I need to get to first, I estimate I can look at this one mid next week.

**Comment by TC25** [comment]
Thanks, Justin!

**Comment by jdbcode** [comment]
Hi TC, this is on our list, we've not forgotten, apologies for the slow review.

**Comment by TC25** [comment]
No worries. Thanks for the update.

**Comment by TC25** [comment]
Any update on this?

**Comment by jdbcode** [comment]
Not yet, still in queue - [Mort's is almost complete](https://github.com/google/earthengine-community/pull/639#issuecomment-1490799790) - yours is next up.

**Comment by jdbcode** [comment]
TC, this is a great tutorial – thanks for submitting it!

Instead of adding suggestions to a review, I did an edit (a reorder and refactor) as I was going through. I hope this is okay with you – I figured it might save both of us time. The reorder was to load the image layers earlier so that if people are executing each code block as they copy and paste into the Code Editor, they don't get an undefined variable error. The refactor is to remove the `if else` chain in the layer/legend `redraw` function. An alternative is to include all of the layer info in a dictionary and subset the relevant visualization params from it when a person selects the layer – it removes some repeated expressions. Additionally, I added an exception to handle NoData in the layers for the inspector and chart to avoid errors.

If you're okay with the changes, please say so; if you're not, please edit the file and commit the changes.

**Comment by TC25** [comment]
Thanks for all the work, Justin! This version looks really good. Definitely going to also help me with my future web apps.

**Comment by jdbcode** [comment]
Excellent! I'll approve the PR which will move the files to Google where they'll be published to the EE Developer Guide within a week. I'll post here the final URL when it goes live.

**Review by jdbcode — APPROVED** [review]

**Comment by jdbcode** [comment]
Hi TC, the tutorial is live!
https://developers.google.com/earth-engine/tutorials/community/creating-web-apps

Thanks for the great contribution!

I've posted an announcement on Twitter: https://twitter.com/jstnbraaten/status/1648460832643362816

If any changes are needed in the future, just submit a pull request.

**Comment by TC25** [comment]
Thanks, Justin!

**Pull request merged**
