### PR TITLE
[Community Tutorials] Set up automated tests and linting

### PR DESCRIPTION
**Pull request by gino-m**
Testing:
- [x] Fork Google Cloud Community Tutorials tests ([link](https://github.com/GoogleCloudPlatform/community/tree/7018369b1ccd28057b3c23220ce6ca95bb00974b/test))
- [x] Adapt tests to EE Community Tutorials (e.g. allow "+", updated paths, etc.)
- [x] Migrate tests to Jasmine test runner

Linting:
- [x] Migrate tests to ES5 (no `=>`, `const`, `let`)
- [x] "Relaxed" eslint config for ES5+Google JS style 
- [x] Other config in .eslint
- [x] Fix lint errors in existing tutorials and tests
- [x] Run lint tests when running tests

Once merged we can set these up to run on PRs via Travis CI or Github Actions.

### CODE REVIEW

**Comment by gino-m** [comment]
> Can linting be applied to the JS code blocks in the MD file? These edits to the .js tutorial files create differences between the JS and MD files. An observation: it produces a result different than `clang-format` - should I continue to `clang-format` my .js files?

Good catch. The strict formatting may make it hard for tutorial authors to format the code in a way that makes the most sense for the tutorial format, and we really should be using unopinionated lint checking anyway. I'll relax the formatting rules and revert the indentation on the .js. 

Created https://github.com/google/earthengine-community/issues/27 to track lint checking of code in Markdown.

**Comment by gino-m** [comment]
Ok, I've disabled indentation checking for now so we can be more flexible wrt formatting/layout. I also added linting and auto fix to code fences in Markdown. Could you PTAL?

Regarding clang-format, did you have it configured to Google style, or another style? If indenting was the only diff w/eslint then with the new config you should be able to continue using that.

**Comment by jdbcode** [comment]
> Regarding clang-format, did you have it configured to Google style, or another style? If indenting was the only diff w/eslint then with the new config you should be able to continue using that.

I did not specify Google as the style, but I just tried now as a test and it produces the same result.

**Comment by gino-m** [comment]
> > Regarding clang-format, did you have it configured to Google style, or another style? If indenting was the only diff w/eslint then with the new config you should be able to continue using that.
> 
> I did not specify Google as the style, but I just tried it now as a test, and it produces the same result.

Thanks for checking.

**Pull request merged**
