### PR TITLE
Update link to image sources

### PR DESCRIPTION
**Pull request by TC25**
I hope it is ok to add the direct link to GIS geography here. I received some emails to do so.

### CODE REVIEW

**Comment by jdbcode** [comment]
Hi TC (@TC25)-- thanks for the pulls request!

A note:

In the future it'd be better to separate the changes into two PRs, one for each tutorial, but no need to alter this PR.

A question:

Just to be clear, this PR includes (1) the image source URL link (2) a new tutorial related to #155? If "yes" to 2, is the tutorial ready for initial review?

**Comment by TC25** [comment]
Justin (@jdbcode), 

1) is correct. 
2) is not actually ready for review yet, and I forgot that I had created a new directory for it which was included in this request. Should I cancel this pull request and just open one for 1) or can you accept part of the changes?

**Comment by jdbcode** [comment]
Is it okay with you if we start fresh i.e. close this PR and do one for the URL update and a second for the new tutorial (when it's ready)? I think that would be cleaner.

**Comment by jdbcode** [comment]
Recommended to split this PR into two. The URL link is now handled in issue #302. Other changes regarding new tutorial draft are not ready for review; refer to issue #155.

**Pull request closed without merging**
