### PR TITLE
Create oceancolor

### PR DESCRIPTION
**Pull request by Elgyii**

### CODE REVIEW

**Comment by jdbcode** [comment]
Hello @Elgyii!

I wasn't expecting this PR, and the files/content makes me think that it may have been submitted by mistake. Can you provide more information about your intention.

**Comment by jdbcode** [comment]
@Elgyii, it looks like #343 supersedes this PR. Is it okay to close this one?

**Comment by Elgyii** [comment]
@jdbcode 
Please go ahead and close this one.
Sorry for the duplication. Initially I was having some trouble creating the pull request.

**Comment by jdbcode** [comment]
No worries :)

**Pull request closed without merging**
